### PR TITLE
Implement Plow

### PR DESCRIPTION
**Pull request by SpaceNerden**
Although the main functionality works, I can't get it to enchant other items. Termi told me its a known issue so I will mark this as draft for now.

### CODE REVIEW

**Comment by dlee13** [comment]
The reason I haven't gotten to switching magnet's item to an enchantment book yet is because enchantments are supposed to be added to the `EnchantmentStorageMeta` that enchanted books have, and our custom anvil code doesn't handle enchantment books with stored enchants yet.

**Comment by SpaceNerden** [comment]
Noted. I'll change it back to a shovel.

**Comment by dlee13** [comment]
The logic in the enchantment's run method looks funky to me. Also, there have been bug reports about Klin's version of the item. Does this resolve the issues?

**Comment by SpaceNerden** [comment]
It has been a while so I'm not entirely sure, but I do remember bug fixing something. I'll have to extend the active time though.

Copied from email, seems like it didn't send it here.

**Comment by SpaceNerden** [comment]
It has been a while so I'm not entirely sure, but I do remember bug fixing
something. I'll have to extend the active time though.

**Pull request closed without merging**
